name: Traefik
version: 3.6.2
slug: traefik
description: |
  Traefik is a modern HTTP reverse proxy and load balancer that makes deploying microservices easy.
arch:
  - amd64
startup: system
init: false
stage: stable
boot: auto
url: https://github.com/AckermannM/home-assistant-addons/tree/master/traefik
ports:
  80/tcp: 80
  443/tcp: 443
ports_description:
  80/tcp: HTTP
  443/tcp: HTTPS
ingress: true
ingress_entry: dashboard/
hassio_role: default
hassio_api: true
panel_icon: mdi:earth-arrow-right
map:
  - config
  - share
  - ssl:rw
options:
  resolverName: ""
  caServer: ""
schema:
  resolverName: str
  caServer: str
